"""Add doctor_id to appointments

Revision ID: 1e64232824be
Revises: 58d2e822d0c4
Create Date: 2025-08-24 22:58:32.969968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e64232824be'
down_revision: Union[str, None] = '58d2e822d0c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('doctor_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'appointments', 'users', ['doctor_id'], ['id'])
    op.add_column('clients', sa.Column('is_blacklisted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'is_blacklisted')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_column('appointments', 'doctor_id')
    # ### end Alembic commands ###
