"""add clinic_name to users

Revision ID: 941d8c45e355
Revises: 01fbd0cfe830
Create Date: 2025-08-22 04:37:49.864718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '941d8c45e355'
down_revision: Union[str, None] = '01fbd0cfe830'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('clinic_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'clinic_name')
    # ### end Alembic commands ###
