"""add doctor_id to appointments

Revision ID: cfca0db85c95
Revises: 77744e0c107f
Create Date: 2025-08-25 15:09:42.998177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfca0db85c95'
down_revision: Union[str, None] = '77744e0c107f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('doctor_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'appointments', 'users', ['doctor_id'], ['id'])
    op.create_foreign_key(None, 'appointments', 'clients', ['client_id'], ['id'])
    op.create_foreign_key(None, 'visitlogs', 'clients', ['client_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'visitlogs', type_='foreignkey')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_column('appointments', 'doctor_id')
    # ### end Alembic commands ###
