"""add doctors table and link to appointments

Revision ID: e609d034b589
Revises: 380779ca710e
Create Date: 2025-08-25 20:35:05.685706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e609d034b589'
down_revision: Union[str, None] = '380779ca710e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinic_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinic_profile_id'), 'clinic_profile', ['id'], unique=False)
    op.create_table('doctors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('specialty', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('clinic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinic_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctors_id'), 'doctors', ['id'], unique=False)
    op.drop_constraint('appointments_doctor_id_fkey', 'appointments', type_='foreignkey')
    op.create_foreign_key(None, 'appointments', 'doctors', ['doctor_id'], ['id'])
    op.add_column('clients', sa.Column('clinic_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'clients', 'clinic_profile', ['clinic_id'], ['id'])
    op.add_column('users', sa.Column('clinic_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'clinic_profile', ['clinic_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'clinic_id')
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_column('clients', 'clinic_id')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.create_foreign_key('appointments_doctor_id_fkey', 'appointments', 'users', ['doctor_id'], ['id'])
    op.drop_index(op.f('ix_doctors_id'), table_name='doctors')
    op.drop_table('doctors')
    op.drop_index(op.f('ix_clinic_profile_id'), table_name='clinic_profile')
    op.drop_table('clinic_profile')
    # ### end Alembic commands ###
